### PR TITLE
feat: formatting ipynb and support for hf datasets.

### PR DESCRIPTION
**Pull request by sayakpaul**
This PR:

* Introduces a small heuristic to process the IPYNB code cell contents and includes them in the final dataframe. 
* Utilities for turning a `pandas` dataframe into a `datasets` compatible dataset and pushes to the Hugging Face Hub. Here's an example dataset: https://hf.co/datasets/coding-assistant-custom/dummy-dataset-sayak. 

@deep-diver could you run the notebook once on your username if the changes look good to you? I could not successfully run it on your username as there was a JSONDecode error when parsing a notebook of your errors (which is weird). 

LMKWYT.

### CODE REVIEW

**Comment by deep-diver** [comment]
looks good to me to remove cells of shell commands! 
once this PR is merged, let me directly push my data

**Comment by sayakpaul** [comment]
Should I merge?

**Comment by deep-diver** [comment]
Yes!

**Comment by sayakpaul** [comment]
@deep-diver once your data is pushed we can collate both of our datasets into a single dataset and have it pushed over the Hub. I will take care of that. 

The GitHub API -- does it not allow the users access other public repositories? For example, are you able to parse my code using the same code (changing the username to `sayakpaul` and the target repositories)?

**Comment by deep-diver** [comment]
I will upload the data file tonight.

About GitHub API, yes we can parse any public repositories, but there is a rate limit(60 requests / hour). Any time we call API(list repos, get list of files, get the contents of each file), they are counted.

**Pull request merged**
